-- DISCLAIMER: using tablespaces and root users like @postgres just to keep simple, 
-- if it gets considered for production environment i strongly suggest a better DB management than this (which was auto generated by pgAdmin)
-- 
-- Table: public.contact_lists

-- DROP TABLE IF EXISTS public.contact_lists;

CREATE TABLE IF NOT EXISTS public.contact_lists
(
    list_id text COLLATE pg_catalog."default" NOT NULL,
    client_id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT contact_lists_pkey PRIMARY KEY (list_id),
    CONSTRAINT fk_contact_lists_clients FOREIGN KEY (client_id)
        REFERENCES public.clients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.contact_lists
    OWNER to postgres;
-- Index: contact_lists_client_id_idx

-- DROP INDEX IF EXISTS public.contact_lists_client_id_idx;

CREATE INDEX IF NOT EXISTS contact_lists_client_id_idx
    ON public.contact_lists USING btree
    (client_id ASC NULLS LAST)
    TABLESPACE pg_default;