-- DISCLAIMER: using tablespaces and root users like @postgres just to keep simple, 
-- if it gets considered for production environment i strongly suggest a better DB management than this (which was auto generated by pgAdmin)
-- 
-- Table: public.emailing_configs

-- DROP TABLE IF EXISTS public.emailing_configs;

CREATE TABLE IF NOT EXISTS public.emailing_configs
(
    client_id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT emailing_configs_pkey PRIMARY KEY (client_id),
    CONSTRAINT fk_emailing_config_clients FOREIGN KEY (client_id)
        REFERENCES public.clients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.emailing_configs
    OWNER to postgres;
-- Index: emailing_configs_client_id_idx

-- DROP INDEX IF EXISTS public.emailing_configs_client_id_idx;

CREATE INDEX IF NOT EXISTS emailing_configs_client_id_idx
    ON public.emailing_configs USING btree
    (client_id ASC NULLS LAST)
    TABLESPACE pg_default;