postgres:
  host: 127.0.0.1
  port: 5432
  user: postgres
  pass: postgres
  db: custom
redis:
  host: localhost
  port: 6379
  pass: randompass
  db: 0

http:
  mailchimp:
    base: https://us9.api.mailchimp.com/3.0
    server: us9
  ometria:
    base: https://api-demo-ingest.ew1-prod.ew1.prod.ometria.cloud